# config.yaml
paths:
  kneaddata_db: /home/User/DB/metagenomic/Kneaddata/hg37
  metaphlan_db: /home/User/DB/metagenomic/metaphlan_databases_vJun23
  humann_nucleotide_db: /home/User/DB/metagenomic/Humann_databases/chocophlan
  humann_protein_db: /home/User/DB/metagenomic/Humann_databases/uniref
  humann_go_db: /home/User/DB/metagenomic/Humann_databases/utility_mapping/utility_mapping/map_go_uniref90.txt.gz
  humann_ko_db: /home/User/DB/metagenomic/Humann_databases/utility_mapping/utility_mapping/map_ko_uniref90.txt.gz
  humann_ec_db: /home/User/DB/metagenomic/Humann_databases/utility_mapping/utility_mapping/map_level4ec_uniref90.txt.gz
  humann_pfam_db: /home/User/DB/metagenomic/Humann_databases/utility_mapping/utility_mapping/map_pfam_uniref90.txt.gz
  humann_eggnog_db: /home/User/DB/metagenomic/Humann_databases/utility_mapping/utility_mapping/map_eggnog_uniref90.txt.gz

tools:
  threads: 8
  kneaddata_env: microbiome-pipeline
  metaphlan_env: microbiome-pipeline
  humann3_env: microbiome-pipeline

samples_dir: /home/User/sample_test
